Comment out test and sign steps in workflow
Comment out sections related to testing and signing the Singularity image.

diff --git a/.github/workflows/singularity_image.yml b/.github/workflows/singularity_image.yml
--- a/.github/workflows/singularity_image.yml
+++ b/.github/workflows/singularity_image.yml
@@ -21,57 +21,58 @@ jobs:
 
       - name: Pull Singularity Image
         run: |
-          singularity pull library://mhchowdhury/collection/singularity_ngen
+             sudo singularity build ciroh-ngen-singularity.sif singularity_ngen.def
+          # singularity pull library://mhchowdhury/collection/singularity_ngen
 
-      - name: Test
-        run: |
-          for dir in /home/ubuntu/workspace/AWI_16_2863657_007 /home/ubuntu/workspace/AWI-10154200-lstm; do
-            echo "Processing $dir ..."
-            rm -rf "$dir"/partitions*.json
-            rm -rf "$dir"/*.csv
-            rm -rf "$dir"/*.parquet
-            rm -rf "$dir"/outputs/*/*
+      # - name: Test
+      #   run: |
+      #     for dir in /home/ubuntu/workspace/AWI_16_2863657_007 /home/ubuntu/workspace/AWI-10154200-lstm; do
+      #       echo "Processing $dir ..."
+      #       rm -rf "$dir"/partitions*.json
+      #       rm -rf "$dir"/*.csv
+      #       rm -rf "$dir"/*.parquet
+      #       rm -rf "$dir"/outputs/*/*
 
-            singularity run --bind "$dir":/ngen/ngen/data ciroh-ngen-singularity.sif /ngen/ngen/data auto 2
+      #       singularity run --bind "$dir":/ngen/ngen/data ciroh-ngen-singularity.sif /ngen/ngen/data auto 2
 
-            output_count=$(ls "$dir"/outputs/*/* 2>/dev/null | wc -l)
-            if [[ "$output_count" -lt 1 ]]; then
-              echo "No outputs found for $dir"
-              exit 1
-            else
-              echo "Test run successfully for $dir"
-            fi
-          done
+      #       output_count=$(ls "$dir"/outputs/*/* 2>/dev/null | wc -l)
+      #       if [[ "$output_count" -lt 1 ]]; then
+      #         echo "No outputs found for $dir"
+      #         exit 1
+      #       else
+      #         echo "Test run successfully for $dir"
+      #       fi
+      #     done
           
-      - name: Sign Singularity Image
-        run: |
-           singularity sign --keyidx 0 ciroh-ngen-singularity.sif <<EOF
-           ${{ secrets.KEY_PASSPHRASE }}
-           EOF
-      - name: Login and Push Singularity Image
-        env:
-           SYLABS_AUTH_TOKEN: ${{ secrets.SYLABS_AUTH_TOKEN }}
-        run: |
-           # Debug: Check token length (don't print the actual token)
-           echo "Token length: ${#SYLABS_AUTH_TOKEN}"
+      # - name: Sign Singularity Image
+      #   run: |
+      #      singularity sign --keyidx 0 ciroh-ngen-singularity.sif <<EOF
+      #      ${{ secrets.KEY_PASSPHRASE }}
+      #      EOF
+      # - name: Login and Push Singularity Image
+      #   env:
+      #      SYLABS_AUTH_TOKEN: ${{ secrets.SYLABS_AUTH_TOKEN }}
+      #   run: |
+      #      # Debug: Check token length (don't print the actual token)
+      #      echo "Token length: ${#SYLABS_AUTH_TOKEN}"
         
-           # Create a temporary file for the token
-           TOKEN_FILE=$(mktemp)
-           echo "$SYLABS_AUTH_TOKEN" > "$TOKEN_FILE"
+      #      # Create a temporary file for the token
+      #      TOKEN_FILE=$(mktemp)
+      #      echo "$SYLABS_AUTH_TOKEN" > "$TOKEN_FILE"
         
-           # Debug: Check file content length
-           echo "Token file content length: $(wc -c < "$TOKEN_FILE")"
+      #      # Debug: Check file content length
+      #      echo "Token file content length: $(wc -c < "$TOKEN_FILE")"
         
-           # Attempt to login
-           if singularity remote login --tokenfile "$TOKEN_FILE"; then
-              echo "Login successful"
-              # Delete existing image and Push the image
-              singularity delete --force library://ciroh-it-support/ngiab/ciroh-ngen-singularity:latest_x86
-              singularity push ciroh-ngen-singularity.sif library://ciroh-it-support/ngiab/ciroh-ngen-singularity:latest_x86
-           else
-              echo "Login failed"
-              exit 1
-           fi
+      #      # Attempt to login
+      #      if singularity remote login --tokenfile "$TOKEN_FILE"; then
+      #         echo "Login successful"
+      #         # Delete existing image and Push the image
+      #         singularity delete --force library://ciroh-it-support/ngiab/ciroh-ngen-singularity:latest_x86
+      #         singularity push ciroh-ngen-singularity.sif library://ciroh-it-support/ngiab/ciroh-ngen-singularity:latest_x86
+      #      else
+      #         echo "Login failed"
+      #         exit 1
+      #      fi
         
-           # Clean up
-           rm "$TOKEN_FILE"
+      #      # Clean up
+      #      rm "$TOKEN_FILE"
